### ISSUE TITLE
Help for newbies

### ISSUE THREAD

**Issue by ibnYusrat** [PetreBoboc/vfs495_ubuntu#1]
Hello, 

A lot of people have been desperately looking for this driver for Ubuntu 16.04, but all of us are not _super-dooper-epic-expert-square_ with Ubuntu. Do you think you can add a readme file for getting this to work for complete noobs?

**Comment by PetreBoboc** [comment]
Added README.md

**Comment by ibnYusrat** [comment]
After the command has run successfully what should be done? I don't see finger print or anything anywhere...

**Comment by PetreBoboc** [comment]
After you run the script, restart, and enroll a finger with fprint_demo by typing into terminal `sudo fprint_demo`.

When you need to log in select your user, press Enter and scan your finger. If it successfully scanned, press Enter and you are logged in.

**Comment by ibnYusrat** [comment]
After running the above command I am getting terminal:
libvfsFprintWrapper.so: cannot open shared object file: No such file or directoryfp:error [fp_dev_open] device initialisation failed, driver=Validity

**Comment by PetreBoboc** [comment]
1. Download and install [this](https://github.com/PetreBoboc/vfs495_ubuntu/raw/master/Packages/validity-sensor-setup_4.5-119_amd64.deb) package
2. Type into terminal `sudo /etc/init.d/vcsFPServiceDaemon start`

* It should look something like this: `[ ok ] Starting vcsFPServiceDaemon (via systemctl): vcsFPServiceDaemon.service.`

3. Type into terminal `sudo update-rc.d vcsFPServiceDaemon defaults`
4. Reboot
5. Log in (with password)
6. Type into terminal `sudo fprint_demo`

After you enroll a finger and restart it should let you log in with the fingerprint.

**Comment by ibnYusrat** [comment]
ibn@ibn:~$ sudo /etc/init.d/vcsFPServiceDaemon start
[sudo] password for ibn: 
/etc/init.d/vcsFPServiceDaemon: 33: .: Can't open /etc/rc.status

Sorry for acting like a complete idiot, but this is what I got after running the first command. (I ran this command after installing the .deb successfully).

**Comment by PetreBoboc** [comment]
* `wget https://raw.githubusercontent.com/PetreBoboc/vfs495_ubuntu/master/vcsFPServiceDaemon && sudo cp vcsFPServiceDaemon /etc/init.d/`
* Reboot
* Try again `sudo /etc/init.d/vcsFPServiceDaemon start`. If it is this: `[ ok ] Starting vcsFPServiceDaemon (via systemctl): vcsFPServiceDaemon.service.` try `fprint_demo` after.

**Comment by ibnYusrat** [comment]
Awesome! So this was the first time I was actually able to scan my finger and it didn't give any error and actually showed my thumb impression on the screen. Somehow the driver seems to be working. But I don't see anything related to finger print on the Ubuntu Login screen. The print_demo did work, I registered my right-hand index finger only and restarted and tried to login but that didn't do any good. I don't see reference of 'finger' related anything on the login screen.

**Comment by PetreBoboc** [comment]
At the log-in screen press Enter, scan your finger and press Enter once again (repeat this until you are successfully logged-in).

**Comment by ibnYusrat** [comment]
Pressing enter at login screen gives me the message saying 'The password you entered is incorrect' because pressing enter causes the already focused password field to submit.

**Comment by PetreBoboc** [comment]
See step 5 form [README.md](https://github.com/PetreBoboc/vfs495_ubuntu/blob/master/README.md)

**Comment by ibnYusrat** [comment]
Perfect! Finally its working! thanks a lot for messing your head with a complete noob!

**Comment by krushnaarengarajan** [comment]
Bus 003 Device 002: ID 138a:003f Validity Sensors, Inc. VFS495 Fingerprint Reader

###have this error after trying solution also and i'm using ubuntu18.04LTS....

krushnaa@krushnaa-HP-ProBook-440-G1:~$ systemctl daemon-reload
krushnaa@krushnaa-HP-ProBook-440-G1:~$ sudo /etc/init.d/vcsFPServiceDaemon start
[ ok ] Starting vcsFPServiceDaemon (via systemctl): vcsFPServiceDaemon.service.
krushnaa@krushnaa-HP-ProBook-440-G1:~$ sudo fprint_demo
libcrypto.so.0.9.8: cannot open shared object file: No such file or directoryfp:error [fp_dev_open] device initialisation failed, driver=Validity

###########thank u advance

**Comment by PetreBoboc** [comment]
@krushnaarengarajan, this repo isn't ready yet for 18.04. I'm working on it. Sorry for the inconvenience.

**Comment by PetreBoboc** [comment]
@krushnaarengarajan, [this](https://github.com/PetreBoboc/vfs495/blob/master/vfs495_ubuntu_18.04.md) should do the trick

You can contact me [here](https://boboc.info/contact)
