### ISSUE TITLE
Debian 9 and fprint_demo: libcrypto issues

### ISSUE THREAD

**Issue by lol768** [PetreBoboc/vfs495_ubuntu#2]
```
$ fprint_demo                                                                            
fprint_demo: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
$ sudo ln --symbolic /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
$ fprint_demo                                                                            
fprint_demo: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/lib/libfprint.so.0)
```

Is there a libfprint that works with a newer libcrypto?

**Comment by Norcoen** [comment]
I'd like to use this on Debian 9, too.
I tried this guide, but it did not work either: https://balintbanyasz.wordpress.com/2015/03/27/get-validity-vfs-495-fingerprint-reader-working-in-ubuntu-14-04/

**Comment by PetreBoboc** [comment]
[This](https://github.com/PetreBoboc/vfs495_ubuntu/blob/master/vfs495_debian.sh) should do the trick. You need to be logged in as root when you run the script.

![capture](https://user-images.githubusercontent.com/19239394/38827123-94546ac6-41ba-11e8-91f5-9e3da2b0875d.JPG)

**Comment by gabolander** [comment]
Hi there mate Petre,
I have Debian 9 testing and succesfulily run the script vfs495_debian.sh.
Everything is in its correct place, vcsFPServiceDaemon up and running (systemctl status says "Active and running") but all the time I start fprint_demo as root, I keep getting "No devices found".
I have a HP ProBook 430 G4 with Validity Sensors VFS495 Fingerprint Reader (ID 138a:003f).
Some kernel modules missing or to load with modprobe?
Any other suggestions? Tnx in advance
G.
