### ISSUE TITLE
fprint_demo: No devices found

### ISSUE THREAD

**Issue by b-fett** [PetreBoboc/vfs495_ubuntu#3]
![image](https://user-images.githubusercontent.com/33630339/37727639-0c77d90e-2d41-11e8-883f-24b821aafeb4.png)

```
dev[~] -> lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 138a:003f Validity Sensors, Inc. VFS495 Fingerprint Reader
Bus 001 Device 004: ID 8087:0a2a Intel Corp. 
Bus 001 Device 003: ID 04f2:b51c Chicony Electronics Co., Ltd 
Bus 001 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
I used script for auto setup.

**Comment by PetreBoboc** [comment]
What version of Ubuntu are you using?

**Comment by b-fett** [comment]
@PetreBoboc Ubuntu 16.04

**Comment by PetreBoboc** [comment]
Ok. I'll see what I can do.

**Comment by PetreBoboc** [comment]
I just tried the autoinstaller on Ubuntu 16.04 and it does not seem to have any problems (fprint_demo recognizes my fingerprint scanner). 

Try the manual version and let me know if it works.

**Comment by b-fett** [comment]
[vfs495_ubuntu.log](https://github.com/PetreBoboc/vfs495_ubuntu/files/1847898/vfs495_ubuntu.log)
This log might be useful.
There are few errors.

**Comment by PetreBoboc** [comment]
Try to manually install this package -> https://github.com/PetreBoboc/vfs495_ubuntu/raw/master/Packages/libfprint_0.0.6-1_amd64.deb

**Comment by b-fett** [comment]
(Reading database ... 235761 files and directories currently installed.)
Preparing to unpack .../libfprint_0.0.6-1_amd64.deb ...
Unpacking libfprint (0.0.6-1) ...
dpkg: error processing archive /home/dev/Downloads/libfprint_0.0.6-1_amd64.deb (--install):
 trying to overwrite '/usr/lib/libfprint.so.0.0.0', which is also in package libfprint0 1:0.7.0-git20171212-1-0ppa1~xenial1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)

**Comment by PetreBoboc** [comment]
Try to uninstall the old libfprint package and install the one I provided link to.

**Comment by b-fett** [comment]
It helped.
But there is one more problem.
While i trying to enroll a finger appears window asking last fingerprint scan for confirmation previous three.
![image](https://user-images.githubusercontent.com/33630339/37917195-7406400e-3126-11e8-88ed-6d68b62897f4.png)
After that program hangs and i can't finish procedure.

**Comment by PetreBoboc** [comment]
Remove all enrolled fingerprints and try again.
It should ask you to enroll a fingerprint three times for the same finger.

**Comment by b-fett** [comment]
I couldn't add any.
But after computer was restarted it worked.

**Comment by PetreBoboc** [comment]
So, can I close the issue? :)

**Comment by b-fett** [comment]
Maybe i'm the only who faced this trouble and it's no need to change install script.
Anyway if it is not so, solution is in here.
Thank for help.
